/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOutputRouteImport } from './routes/_app/output'
import { Route as AppVideosIndexRouteImport } from './routes/_app/videos/index'
import { Route as AppImageIdIndexRouteImport } from './routes/_app/$imageId/index'
import { Route as AppVideosVideoIdIndexRouteImport } from './routes/_app/videos/$videoId/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOutputRoute = AppOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosIndexRoute = AppVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AppRoute,
} as any)
const AppImageIdIndexRoute = AppImageIdIndexRouteImport.update({
  id: '/$imageId/',
  path: '/$imageId/',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosVideoIdIndexRoute = AppVideosVideoIdIndexRouteImport.update({
  id: '/videos/$videoId/',
  path: '/videos/$videoId/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/output': typeof AppOutputRoute
  '/settings': typeof AppSettingsRoute
  '/$imageId/': typeof AppImageIdIndexRoute
  '/videos/': typeof AppVideosIndexRoute
  '/videos/$videoId/': typeof AppVideosVideoIdIndexRoute
}
export interface FileRoutesByTo {
  '/output': typeof AppOutputRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/$imageId': typeof AppImageIdIndexRoute
  '/videos': typeof AppVideosIndexRoute
  '/videos/$videoId': typeof AppVideosVideoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/output': typeof AppOutputRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$imageId/': typeof AppImageIdIndexRoute
  '/_app/videos/': typeof AppVideosIndexRoute
  '/_app/videos/$videoId/': typeof AppVideosVideoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/output'
    | '/settings'
    | '/$imageId/'
    | '/videos/'
    | '/videos/$videoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/output'
    | '/settings'
    | '/'
    | '/$imageId'
    | '/videos'
    | '/videos/$videoId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/output'
    | '/_app/settings'
    | '/_app/'
    | '/_app/$imageId/'
    | '/_app/videos/'
    | '/_app/videos/$videoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/output': {
      id: '/_app/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof AppOutputRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos/': {
      id: '/_app/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AppVideosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$imageId/': {
      id: '/_app/$imageId/'
      path: '/$imageId'
      fullPath: '/$imageId/'
      preLoaderRoute: typeof AppImageIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos/$videoId/': {
      id: '/_app/videos/$videoId/'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId/'
      preLoaderRoute: typeof AppVideosVideoIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOutputRoute: typeof AppOutputRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppImageIdIndexRoute: typeof AppImageIdIndexRoute
  AppVideosIndexRoute: typeof AppVideosIndexRoute
  AppVideosVideoIdIndexRoute: typeof AppVideosVideoIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOutputRoute: AppOutputRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppImageIdIndexRoute: AppImageIdIndexRoute,
  AppVideosIndexRoute: AppVideosIndexRoute,
  AppVideosVideoIdIndexRoute: AppVideosVideoIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
